### ISSUE TITLE
clear cache function

### ISSUE THREAD

**Issue by mpadge** [hypertidy/ceramic#10]
[`R.cache`](https://github.com/HenrikBengtsson/R.cache/blob/master/R/clearCache.R) just has an explicit function that it is up to the user to call, so I'd suggest you could safely presume that this is current "best practice". Simple to implement such a function here, because the cache dir is fixed - just remove the whole shebang with `clear_ceramic_cache()`.

**Comment by mdsumner** [comment]
Totally agree - thanks for the impetus ;)  

I don't want to test it though ...  70e762c2da43f89b4e57b8bd41d109d9ba01db55

**Comment by mdsumner** [comment]
Is this suitable now? I've seen some funny errors still

**Comment by mpadge** [comment]
I'll have a look asap...

**Comment by mdsumner** [comment]
I think this is done.
