### ISSUE TITLE
generalize provider

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/ceramic#14]
A fair bit of refactoring is required

- [x] type to include "elevation-tiles-prod", and just let that set dictate the provider
- [ ] provider choice will be configurable, e.g. custom mapbox, format jpg/png (more needed)
- [x] get_loc() to return file list, not a raster

Each type will dispatch to the right "provider_string()" function, zoom, x, y are templated - and somehow mapbox be able to choose format. 

`get_loc` may become a `get_<provider>`, and so the loc handling become new functions

**Comment by mdsumner** [comment]
@jhollist just FYI, made some progres here in "general" branch currently at ae9972fb, would be great if you could explore!  Lots still to do but was happy with how I could unpick the mapbox stuff

(I haven't tried any of the tile-list functions in ceramic yet ...)


``` r
lake <- elevatr::lake
library(ceramic)  
library(raster)
#> Loading required package: sp
sat <- cc_location(lake, type = "mapbox.satellite")

out <- cc_location(lake, type = "mapbox.outdoors")

ter <- cc_elevation(lake)

aws <- cc_location(lake, type = "elevation-tiles-prod")
op <- par(mfrow = c(2, 2))
plotRGB(sat)
plotRGB(out)
greys <- grey(seq(0.1, 1, length = 56))
plotRGB(sat); plot(ter, col = greys, add = TRUE) ## easy plot position copy
plotRGB(sat); plot(aws, col = greys, add = TRUE)
```

![](https://i.imgur.com/5sOhOAu.png)

``` r
par(op)
```

<sup>Created on 2019-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mdsumner** [comment]
Now in master, ignore all branches

**Comment by jhollist** [comment]
Thanks...  Slammed this week.  Hope to take a look next week.

**Comment by mdsumner** [comment]
there's some extra services here, doesn't seem to cache the tiles natively but not sure

https://github.com/16EAGLE/basemap

**Comment by mdsumner** [comment]
won't do, use hypertidy/dsn and other sources for online imagery
