### ISSUE TITLE
new providers, mostly osm

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/ceramic#33]
check out this list

https://github.com/16EAGLE/basemaps/blob/master/R/internal.R

- [ ] put mapbox aside, don't make it the default *unless* the api key is found
- [ ] need smart way to specify provider and style (change from type)
 
etc.

**Comment by mdsumner** [comment]
Here's another one: https://github.com/walkerke/mapboxapi

**Comment by jdsher** [comment]
Just found this package and I think it will be a huge help on some projects I have - is there currently a way to fetch tiles from different providers using `base_url`? Like the generic Stamen Toner tiles?

**Comment by mdsumner** [comment]
I don't really know ... but this worked for me: 

```R
img <- cc_location(cbind(147, -42), buffer = 1e5, base_url = "https://stamen-tiles-a.a.ssl.fastly.net/toner/{zoom}/{x}/{y}.png")
Preparing to download: 16 tiles at zoom = 9 from 
https://stamen-tiles-a.a.ssl.fastly.net/toner/
```

Things are are pretty uncertain right now with ceramic given #31 so I'm not sure how useful that is

**Comment by jdsher** [comment]
Thank you very much, that works perfectly for my needs.

**Comment by mdsumner** [comment]
I expect ceramic will continue to support mapbox satellite and terrain-rgb, and aws elevation - but I'd advise to use the sources listed in hypertidy/dsn for the others
