### ISSUE TITLE
easy option to extract X,Y,Z,R,B,G

### ISSUE THREAD

**Issue by djouallah** [hypertidy/ceramic#35]
it will be nice to have an option to easily extract x,y,z and RGB values in a dataframe.

**Comment by mdsumner** [comment]
the raster package has `as.data.frame()` methods for single-layer and multi-layer (RGB) Raster objects, use argument `xy = TRUE` to get the centre coordinates of each cell. 

I do think it's an interesting idea, though, it would be nice to be able to get a 4-layer raster with a single function call, and I'm thinking about it.

**Comment by djouallah** [comment]
I am already using this script
library(raster)
library(ceramic)

cc <- ceramic::cc_location(cbind(5.529993,23.290084), buffer = c(2000, 2000), zoom = 15)
el <- ceramic::cc_elevation(cc)
x <- aggregate(el,2)
df <- as.data.frame(x, xy=TRUE)

how to get the RGB values from cc and merge it with df

my purpose is to get a df with x,y,z,r,g,b  which I think is called a point cloud and plot it in a different software.

my issue is I don't even know the words to use to google for a solution :)

**Comment by mdsumner** [comment]
you should be able to give the zoom argument to cc_elevation and get the same output (but I think maybe I mucked this up on the CRAN version)

to get `x` (a less perfect solution than matching them as it's supposed to work without my bug/s)

```R
x <- projectRaster(el, cc)

```

then see that x and cc objects have the same structure, so give the same as.data.frame() (but different data columns)

**Comment by djouallah** [comment]
sorry, I think it is lost in Translation
using this 
library(raster)
library(ceramic)
library(bigrquery)
#bq_auth(scopes = "https://www.googleapis.com/auth/bigquery")
Sys.setenv(MAPBOX_API_KEY = "4eVKWQss7GZQ")
cc <- ceramic::cc_location(cbind(5.529993,23.290084), buffer = c(2000, 2000), zoom = 15)
el <- ceramic::cc_elevation(cc)
x <- projectRaster(el, cc)
df <- as.data.frame(x, xy=TRUE)

df is giving me x,y,layer which I have it already, I am looking to get access for the color values for every coordinates

**Comment by mdsumner** [comment]
as.data.frame(cc) will give the the RGB columns, cbind to the other one

**Comment by djouallah** [comment]
a little problem the two dataframe do not have the same numbers of rows, how to join them ?

![image](https://user-images.githubusercontent.com/12554469/88549424-a06c1900-d063-11ea-9cf1-4171532ee76e.png)

**Comment by djouallah** [comment]
I think, I am getting there
library(raster)
library(ceramic)
cc <- ceramic::cc_location(cbind(5.529993,23.290084), buffer = c(2000, 2000), zoom = 15)
el <- ceramic::cc_elevation(cc)
el1 <- resample(el, cc, method = "bilinear")
x <- raster::merge(cc, el1)
df <- as.data.frame(x,xy=TRUE)
df1 <- as.data.frame(el1,xy=TRUE)

**Comment by djouallah** [comment]
I think I got it 

library(raster)
library(ceramic)
library(bigrquery)

cc <- ceramic::cc_location(cbind(5.529993,23.290084), buffer = c(2000, 2000), zoom = 15)
el <- ceramic::cc_elevation(cc)
el1 <- resample(el, cc, method = "bilinear")
 
 df1 <- as.data.frame(cc,xy=TRUE)
 df2 <- as.data.frame(el1,xy=TRUE)
df <- merge(x = df1, y = df2, by = c("x", "y"), all.x = TRUE)
