### ISSUE TITLE
Error on cc_location: "could not find function 'cellsFromExtent'"

### ISSUE THREAD

**Issue by ajlyons** [hypertidy/ceramic#39]
Thank you for putting together this awesome package! I encountered the following reproducible error on some of the sample code:

# restart R
library(ceramic)
im <- cc_location(cbind(136, -34), buffer = c(1e6, 5e5), type = "mapbox.satellite")

https://api.mapbox.com/v4/mapbox.satellite/
Error in cellsFromExtent(out, .x) : 
  **could not find function "cellsFromExtent"**

The error goes away if I first run library(raster).

I'm not sure which internal function is generating this error message, but it could probably be fixed by adding the following:

@importFrom raster cellsFromExtent

**Comment by mdsumner** [comment]
ah thanks, it's already fixed on github - just not on CRAN yet
